version: '3.9'
services:
  ray:
    build:
      context: ../
      dockerfile: deployment/Dockerfile.ray
    ports:
      - "8000:8000"
  api:
    build:
      context: ../
      dockerfile: deployment/Dockerfile.api
    ports:
      - "5000:5000"
    depends_on:
      - ray
